export const pokemonTypesObject = {
	fire: {
		id: 1,
		name: 'fire',
		isEffectiveAgainst: ['grass', 'ice', 'steel', 'bug'],
		isNotEffectiveAgainst: ['water', 'dragon', 'fire', 'rock'],
		isResistantAgainst: ['steel', 'bug', 'fire', 'fairy', 'ice', 'grass'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['water', 'rock', 'ground'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'dragon',
			'electric',
			'ghost',
			'fighting',
			'normal',
			'dark',
			'poison',
			'flying',
		],
	},
	water: {
		id: 2,
		name: 'water',
		isEffectiveAgainst: ['fire', 'rock', 'ground'],
		isNotEffectiveAgainst: ['water', 'dragon', 'grass'],
		isResistantAgainst: ['steel', 'water', 'fire', 'ice'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['electric', 'grass'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'bug',
			'dragon',
			'ghost',
			'fairy',
			'fighting',
			'normal',
			'rock',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	grass: {
		id: 3,
		name: 'grass',
		isEffectiveAgainst: ['water', 'rock', 'ground'],
		isNotEffectiveAgainst: [
			'steel',
			'bug',
			'dragon',
			'fire',
			'grass',
			'poison',
			'flying',
		],
		isResistantAgainst: ['water', 'electric', 'grass', 'ground'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['bug', 'fire', 'ice', 'poison', 'flying'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'steel',
			'dragon',
			'ghost',
			'fairy',
			'fighting',
			'normal',
			'rock',
			'dark',
		],
	},
	psychic: {
		id: 4,
		name: 'psychic',
		isEffectiveAgainst: ['fighting', 'poison'],
		isNotEffectiveAgainst: ['steel', 'psychic'],
		isResistantAgainst: ['fighting', 'psychic'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['bug', 'ghost', 'dark'],
		isImmuneAgainstMyAttacks: ['dark'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'steel',
			'dragon',
			'electric',
			'fairy',
			'ice',
			'normal',
			'rock',
			'ground',
			'poison',
			'flying',
		],
	},
	steel: {
		id: 5,
		name: 'steel',
		isEffectiveAgainst: ['fairy', 'ice', 'rock'],
		isNotEffectiveAgainst: ['steel', 'water', 'electric', 'fire'],
		isResistantAgainst: [
			'steel',
			'bug',
			'dragon',
			'fairy',
			'ice',
			'normal',
			'grass',
			'psychic',
			'rock',
			'flying',
		],
		hasImmunityAgainst: ['poison'],
		isEffectiveAgainstMe: ['fire', 'fighting', 'ground'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: ['water', 'electric', 'ghost', 'dark'],
	},
	bug: {
		id: 6,
		name: 'bug',
		isEffectiveAgainst: ['grass', 'psychic', 'dark'],
		isNotEffectiveAgainst: [
			'steel',
			'ghost',
			'fire',
			'fairy',
			'fighting',
			'poison',
			'flying',
		],
		isResistantAgainst: ['fighting', 'grass', 'ground'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['fire', 'rock', 'flying'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'water',
			'psychic',
			'steel',
			'bug',
			'dragon',
			'electric',
			'ghost',
			'fairy',
			'ice',
			'normal',
			'dark',
			'poison',
		],
	},
	dragon: {
		id: 7,
		name: 'dragon',
		isEffectiveAgainst: ['dragon'],
		isNotEffectiveAgainst: ['steel'],
		isResistantAgainst: ['water', 'electric', 'fire', 'grass'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['dragon', 'fairy', 'ice'],
		isImmuneAgainstMyAttacks: ['fairy'],
		isNeutralAgainstMe: [
			'psychic',
			'steel',
			'bug',
			'ghost',
			'fighting',
			'normal',
			'rock',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	electric: {
		id: 8,
		name: 'electric',
		isEffectiveAgainst: ['water', 'flying'],
		isNotEffectiveAgainst: ['dragon', 'electric', 'grass'],
		isResistantAgainst: ['steel', 'electric', 'flying'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['ground'],
		isImmuneAgainstMyAttacks: ['ground'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'bug',
			'dragon',
			'ghost',
			'fairy',
			'ice',
			'fighting',
			'normal',
			'rock',
			'dark',
			'poison',
		],
	},
	ghost: {
		id: 9,
		name: 'ghost',
		isEffectiveAgainst: ['ghost', 'psychic'],
		isNotEffectiveAgainst: ['dark'],
		isResistantAgainst: ['bug', 'poison'],
		hasImmunityAgainst: ['fighting', 'normal'],
		isEffectiveAgainstMe: ['ghost', 'dark'],
		isImmuneAgainstMyAttacks: ['normal'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'steel',
			'dragon',
			'electric',
			'fairy',
			'ice',
			'rock',
			'ground',
			'flying',
		],
	},
	fairy: {
		id: 10,
		name: 'fairy',
		isEffectiveAgainst: ['dragon', 'fighting', 'dark'],
		isNotEffectiveAgainst: ['steel', 'fire', 'poison'],
		isResistantAgainst: ['bug', 'fighting', 'dark'],
		hasImmunityAgainst: ['dragon'],
		isEffectiveAgainstMe: ['steel', 'poison'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'electric',
			'ghost',
			'ice',
			'normal',
			'rock',
			'ground',
			'fairy',
			'flying',
		],
	},
	ice: {
		id: 11,
		name: 'ice',
		isEffectiveAgainst: ['dragon', 'grass', 'ground', 'flying'],
		isNotEffectiveAgainst: ['steel', 'water', 'fire', 'ice'],
		isResistantAgainst: ['ice'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['steel', 'fire', 'fighting', 'rock'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'water',
			'grass',
			'psychic',
			'bug',
			'dragon',
			'electric',
			'ghost',
			'fairy',
			'normal',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	fighting: {
		id: 12,
		name: 'fighting',
		isEffectiveAgainst: ['steel', 'ice', 'normal', 'rock', 'dark'],
		isNotEffectiveAgainst: ['bug', 'fairy', 'psychic', 'poison', 'flying'],
		isResistantAgainst: ['bug', 'rock', 'dark'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['fairy', 'psychic', 'flying'],
		isImmuneAgainstMyAttacks: ['ghost'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'steel',
			'dragon',
			'electric',
			'ghost',
			'ice',
			'fighting',
			'normal',
			'ground',
			'poison',
		],
	},
	normal: {
		id: 13,
		name: 'normal',
		isEffectiveAgainst: [],
		isNotEffectiveAgainst: ['steel', 'rock'],
		isResistantAgainst: [],
		hasImmunityAgainst: ['ghost'],
		isEffectiveAgainstMe: ['fighting'],
		isImmuneAgainstMyAttacks: ['ghost'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'steel',
			'bug',
			'dragon',
			'electric',
			'fairy',
			'ice',
			'normal',
			'rock',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	rock: {
		id: 14,
		name: 'rock',
		isEffectiveAgainst: ['bug', 'fire', 'ice', 'flying'],
		isNotEffectiveAgainst: ['steel', 'fighting', 'ground'],
		isResistantAgainst: ['fire', 'normal', 'poison', 'flying'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['steel', 'water', 'fighting', 'grass', 'ground'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'bug',
			'dragon',
			'electric',
			'ghost',
			'fairy',
			'ice',
			'rock',
			'dark',
		],
	},
	dark: {
		id: 15,
		name: 'dark',
		isEffectiveAgainst: ['ghost', 'psychic'],
		isNotEffectiveAgainst: ['fairy', 'fighting', 'dark'],
		isResistantAgainst: ['ghost', 'dark'],
		hasImmunityAgainst: ['psychic'],
		isEffectiveAgainstMe: ['bug', 'fairy', 'fighting'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'steel',
			'dragon',
			'electric',
			'ice',
			'normal',
			'rock',
			'ground',
			'poison',
			'flying',
		],
	},
	ground: {
		id: 16,
		name: 'ground',
		isEffectiveAgainst: ['steel', 'electric', 'fire', 'rock', 'poison'],
		isNotEffectiveAgainst: ['bug', 'grass'],
		isResistantAgainst: ['rock', 'poison'],
		hasImmunityAgainst: ['electric'],
		isEffectiveAgainstMe: ['water', 'ice', 'grass'],
		isImmuneAgainstMyAttacks: ['flying'],
		isNeutralAgainstMe: [
			'fire',
			'psychic',
			'steel',
			'bug',
			'dragon',
			'ghost',
			'fairy',
			'fighting',
			'normal',
			'dark',
			'ground',
			'flying',
		],
	},
	poison: {
		id: 17,
		name: 'poison',
		isEffectiveAgainst: ['fairy', 'grass'],
		isNotEffectiveAgainst: ['ghost', 'rock', 'ground', 'poison'],
		isResistantAgainst: ['bug', 'fairy', 'fighting', 'grass', 'poison'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['psychic', 'ground'],
		isImmuneAgainstMyAttacks: ['steel'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'steel',
			'dragon',
			'electric',
			'ghost',
			'ice',
			'normal',
			'rock',
			'dark',
			'flying',
		],
	},
	flying: {
		id: 18,
		name: 'flying',
		isEffectiveAgainst: ['bug', 'fighting', 'grass'],
		isNotEffectiveAgainst: ['steel', 'electric', 'rock'],
		isResistantAgainst: ['bug', 'fighting', 'grass'],
		hasImmunityAgainst: ['ground'],
		isEffectiveAgainstMe: ['electric', 'ice', 'rock'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'psychic',
			'steel',
			'dragon',
			'ghost',
			'fairy',
			'normal',
			'dark',
			'poison',
			'flying',
		],
	},
};

export const pokemonTypesArray = [
	{
		id: 1,
		name: 'fire',
		isEffectiveAgainst: ['grass', 'ice', 'steel', 'bug'],
		isNotEffectiveAgainst: ['water', 'dragon', 'fire', 'rock'],
		isResistantAgainst: ['steel', 'bug', 'fire', 'fairy', 'ice', 'grass'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['water', 'rock', 'ground'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'dragon',
			'electric',
			'ghost',
			'fighting',
			'normal',
			'dark',
			'poison',
			'flying',
		],
	},
	{
		id: 2,
		name: 'water',
		isEffectiveAgainst: ['fire', 'rock', 'ground'],
		isNotEffectiveAgainst: ['water', 'dragon', 'grass'],
		isResistantAgainst: ['steel', 'water', 'fire', 'ice'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['electric', 'grass'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'bug',
			'dragon',
			'ghost',
			'fairy',
			'fighting',
			'normal',
			'rock',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	{
		id: 3,
		name: 'grass',
		isEffectiveAgainst: ['water', 'rock', 'ground'],
		isNotEffectiveAgainst: [
			'steel',
			'bug',
			'dragon',
			'fire',
			'grass',
			'poison',
			'flying',
		],
		isResistantAgainst: ['water', 'electric', 'grass', 'ground'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['bug', 'fire', 'ice', 'poison', 'flying'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'steel',
			'dragon',
			'ghost',
			'fairy',
			'fighting',
			'normal',
			'rock',
			'dark',
		],
	},
	{
		id: 4,
		name: 'psychic',
		isEffectiveAgainst: ['fighting', 'poison'],
		isNotEffectiveAgainst: ['steel', 'psychic'],
		isResistantAgainst: ['fighting', 'psychic'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['bug', 'ghost', 'dark'],
		isImmuneAgainstMyAttacks: ['dark'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'steel',
			'dragon',
			'electric',
			'fairy',
			'ice',
			'normal',
			'rock',
			'ground',
			'poison',
			'flying',
		],
	},
	{
		id: 5,
		name: 'steel',
		isEffectiveAgainst: ['fairy', 'ice', 'rock'],
		isNotEffectiveAgainst: ['steel', 'water', 'electric', 'fire'],
		isResistantAgainst: [
			'steel',
			'bug',
			'dragon',
			'fairy',
			'ice',
			'normal',
			'grass',
			'psychic',
			'rock',
			'flying',
		],
		hasImmunityAgainst: ['poison'],
		isEffectiveAgainstMe: ['fire', 'fighting', 'ground'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: ['water', 'electric', 'ghost', 'dark'],
	},
	{
		id: 6,
		name: 'bug',
		isEffectiveAgainst: ['grass', 'psychic', 'dark'],
		isNotEffectiveAgainst: [
			'steel',
			'ghost',
			'fire',
			'fairy',
			'fighting',
			'poison',
			'flying',
		],
		isResistantAgainst: ['fighting', 'grass', 'ground'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['fire', 'rock', 'flying'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'water',
			'psychic',
			'steel',
			'bug',
			'dragon',
			'electric',
			'ghost',
			'fairy',
			'ice',
			'normal',
			'dark',
			'poison',
		],
	},
	{
		id: 7,
		name: 'dragon',
		isEffectiveAgainst: ['dragon'],
		isNotEffectiveAgainst: ['steel'],
		isResistantAgainst: ['water', 'electric', 'fire', 'grass'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['dragon', 'fairy', 'ice'],
		isImmuneAgainstMyAttacks: ['fairy'],
		isNeutralAgainstMe: [
			'psychic',
			'steel',
			'bug',
			'ghost',
			'fighting',
			'normal',
			'rock',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	{
		id: 8,
		name: 'electric',
		isEffectiveAgainst: ['water', 'flying'],
		isNotEffectiveAgainst: ['dragon', 'electric', 'grass'],
		isResistantAgainst: ['steel', 'electric', 'flying'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['ground'],
		isImmuneAgainstMyAttacks: ['ground'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'bug',
			'dragon',
			'ghost',
			'fairy',
			'ice',
			'fighting',
			'normal',
			'rock',
			'dark',
			'poison',
		],
	},
	{
		id: 9,
		name: 'ghost',
		isEffectiveAgainst: ['ghost', 'psychic'],
		isNotEffectiveAgainst: ['dark'],
		isResistantAgainst: ['bug', 'poison'],
		hasImmunityAgainst: ['fighting', 'normal'],
		isEffectiveAgainstMe: ['ghost', 'dark'],
		isImmuneAgainstMyAttacks: ['normal'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'steel',
			'dragon',
			'electric',
			'fairy',
			'ice',
			'rock',
			'ground',
			'flying',
		],
	},
	{
		id: 10,
		name: 'fairy',
		isEffectiveAgainst: ['dragon', 'fighting', 'dark'],
		isNotEffectiveAgainst: ['steel', 'fire', 'poison'],
		isResistantAgainst: ['bug', 'fighting', 'dark'],
		hasImmunityAgainst: ['dragon'],
		isEffectiveAgainstMe: ['steel', 'poison'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'electric',
			'ghost',
			'ice',
			'normal',
			'rock',
			'ground',
			'fairy',
			'flying',
		],
	},
	{
		id: 11,
		name: 'ice',
		isEffectiveAgainst: ['dragon', 'grass', 'ground', 'flying'],
		isNotEffectiveAgainst: ['steel', 'water', 'fire', 'ice'],
		isResistantAgainst: ['ice'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['steel', 'fire', 'fighting', 'rock'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'water',
			'grass',
			'psychic',
			'bug',
			'dragon',
			'electric',
			'ghost',
			'fairy',
			'normal',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	{
		id: 12,
		name: 'fighting',
		isEffectiveAgainst: ['steel', 'ice', 'normal', 'rock', 'dark'],
		isNotEffectiveAgainst: ['bug', 'fairy', 'psychic', 'poison', 'flying'],
		isResistantAgainst: ['bug', 'rock', 'dark'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['fairy', 'psychic', 'flying'],
		isImmuneAgainstMyAttacks: ['ghost'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'steel',
			'dragon',
			'electric',
			'ghost',
			'ice',
			'fighting',
			'normal',
			'ground',
			'poison',
		],
	},
	{
		id: 13,
		name: 'normal',
		isEffectiveAgainst: [],
		isNotEffectiveAgainst: ['steel', 'rock'],
		isResistantAgainst: [],
		hasImmunityAgainst: ['ghost'],
		isEffectiveAgainstMe: ['fighting'],
		isImmuneAgainstMyAttacks: ['ghost'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'psychic',
			'steel',
			'bug',
			'dragon',
			'electric',
			'fairy',
			'ice',
			'normal',
			'rock',
			'dark',
			'ground',
			'poison',
			'flying',
		],
	},
	{
		id: 14,
		name: 'rock',
		isEffectiveAgainst: ['bug', 'fire', 'ice', 'flying'],
		isNotEffectiveAgainst: ['steel', 'fighting', 'ground'],
		isResistantAgainst: ['fire', 'normal', 'poison', 'flying'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['steel', 'water', 'fighting', 'grass', 'ground'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'psychic',
			'bug',
			'dragon',
			'electric',
			'ghost',
			'fairy',
			'ice',
			'rock',
			'dark',
		],
	},
	{
		id: 15,
		name: 'dark',
		isEffectiveAgainst: ['ghost', 'psychic'],
		isNotEffectiveAgainst: ['fairy', 'fighting', 'dark'],
		isResistantAgainst: ['ghost', 'dark'],
		hasImmunityAgainst: ['psychic'],
		isEffectiveAgainstMe: ['bug', 'fairy', 'fighting'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'grass',
			'steel',
			'dragon',
			'electric',
			'ice',
			'normal',
			'rock',
			'ground',
			'poison',
			'flying',
		],
	},
	{
		id: 16,
		name: 'ground',
		isEffectiveAgainst: ['steel', 'electric', 'fire', 'rock', 'poison'],
		isNotEffectiveAgainst: ['bug', 'grass'],
		isResistantAgainst: ['rock', 'poison'],
		hasImmunityAgainst: ['electric'],
		isEffectiveAgainstMe: ['water', 'ice', 'grass'],
		isImmuneAgainstMyAttacks: ['flying'],
		isNeutralAgainstMe: [
			'fire',
			'psychic',
			'steel',
			'bug',
			'dragon',
			'ghost',
			'fairy',
			'fighting',
			'normal',
			'dark',
			'ground',
			'flying',
		],
	},
	{
		id: 17,
		name: 'poison',
		isEffectiveAgainst: ['fairy', 'grass'],
		isNotEffectiveAgainst: ['ghost', 'rock', 'ground', 'poison'],
		isResistantAgainst: ['bug', 'fairy', 'fighting', 'grass', 'poison'],
		hasImmunityAgainst: [],
		isEffectiveAgainstMe: ['psychic', 'ground'],
		isImmuneAgainstMyAttacks: ['steel'],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'steel',
			'dragon',
			'electric',
			'ghost',
			'ice',
			'normal',
			'rock',
			'dark',
			'flying',
		],
	},
	{
		id: 18,
		name: 'flying',
		isEffectiveAgainst: ['bug', 'fighting', 'grass'],
		isNotEffectiveAgainst: ['steel', 'electric', 'rock'],
		isResistantAgainst: ['bug', 'fighting', 'grass'],
		hasImmunityAgainst: ['ground'],
		isEffectiveAgainstMe: ['electric', 'ice', 'rock'],
		isImmuneAgainstMyAttacks: [],
		isNeutralAgainstMe: [
			'fire',
			'water',
			'psychic',
			'steel',
			'dragon',
			'ghost',
			'fairy',
			'normal',
			'dark',
			'poison',
			'flying',
		],
	},
];
