'use client';

import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './Components/Navbar/Navbar';
import { Toaster } from 'sonner';
import { PrimeReactProvider } from 'primereact/api';
import { SelectionProvider } from './utils/context/SelectionContext';
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import 'primereact/resources/themes/lara-light-indigo/theme.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<DndProvider backend={HTML5Backend}>
					<PrimeReactProvider>
						<SelectionProvider>
							<Navbar />
							{children}
							<Toaster
								position='bottom-left'
								richColors
								duration={2000}
							/>
						</SelectionProvider>
					</PrimeReactProvider>
				</DndProvider>
			</body>
		</html>
	);
}
